In [ ]:
import torch
print(torch.__version__)

In [19]:
#Scalar
Scalar=torch.tensor(2)
print("The Scalar Value is ",Scalar)
print("The Dimensional of the Scalar is ",Scalar.ndim)
print("The Shape of the Scalar is ",Scalar.shape)
print("The Printing the scalar value is ",Scalar.item())
#Vector: It is Mathematical and Physical entity that possesses (which have or own )both magnitube(size or length) and Direction
Vector=torch.tensor([1,2,3,4])
print("The Vector is ",Vector)
print("The Shape of the Vector is" ,Vector.shape)
print("The Dimensional fo the Vector is ",Vector.shape)
print("The Size of the Vector is ",Vector.size)
#Matrix:The Rectangular Arrnagement of the elements is Called Matrix.
Matrix=torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print("The Matrix is ",Matrix)
print("The Shape of the Matrix is ",Matrix.shape)
print("The Dimensional of the Matrix is ",Matrix.ndim)
#Tensor:Tensor can be Defined as combining the several matrixes or Multidimensional array is Called Tensor
Tensor=torch.tensor([[[1,2],
                      [3,4]],
                      [[5,6],
                       [7,8]],
                      [[8,9],
                       [10,11]]])
print("The Tensor is ",Tensor)
print("The Shape of the Tensor is ",Tensor.shape)
print("The Dimensional of the Tensor is ",Tensor.ndim)
print("The length of the Tensor is ",len(Tensor))

The Scalar Value is  tensor(2)
The Dimensional of the Scalar is  0
The Shape of the Scalar is  torch.Size([])
The Printing the scalar value is  2
The Vector is  tensor([1, 2, 3, 4])
The Shape of the Vector is torch.Size([4])
The Dimensional fo the Vector is  torch.Size([4])
The Size of the Vector is  <built-in method size of Tensor object at 0x7f1f7416f570>
The Matrix is  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The Shape of the Matrix is  torch.Size([3, 3])
The Dimensional of the Matrix is  2
The Tensor is  tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 8,  9],
         [10, 11]]])
The Shape of the Tensor is  torch.Size([3, 2, 2])
The Dimensional of the Tensor is  3
The length of the Tensor is  3


Random Tensors

In [31]:
#Creating the Random Tensor
random_tensor=torch.rand(size=(3,4),dtype=torch.float64)
print("The Random Tensor is ",random_tensor)
print("The Data type of the Tensor is ",random_tensor.dtype)


The Random Tensor is  tensor([[0.5533, 0.2546, 0.7040, 0.6210],
        [0.9728, 0.3638, 0.6339, 0.3858],
        [0.3528, 0.1042, 0.7090, 0.2828]], dtype=torch.float64)
The Data type of the Tensor is  torch.float64


Zeros and Ones

In [41]:
#Creating the Zeros Tensor
Zeros=torch.zeros(size=(3,4))
print(Zeros,Zeros.dtype,Zeros.ndim,Zeros.shape)
#Creating the ones Tensor
Ones=torch.ones(size=(4,3,4))
print(Ones)
print("The Shape of the Tensor is ",Ones.shape)
print("The Dimensional fo the Array",Ones.ndim)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32 2 torch.Size([3, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
The Shape of the Tensor is  torch.Size([4, 3, 4])
The Dimensional fo the Array 3


 Creating the Range and Tensor

In [51]:
Zeros_to_ten_deprecatedd=torch.arange(0,10)
print(Zeros_to_ten_deprecatedd)
#Creating Tensor of the Zeros And The input should be Tensor only
ten_Zeros=torch.zeros_like(input=Zeros_to_ten_deprecatedd)
print(ten_Zeros)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


Tensor Datatypes