In [1]:
import torch
print(torch.__version__)

2.8.0+cpu


In [1]:
import torch
Tensor=torch.tensor([1,2,3,4])
#Adding the 10 to all Elements present in the Tensor
print(Tensor+10)
print(Tensor.add(10))
#Subtracting the 2 to all Elements present in the Tensor
print(Tensor-2)
print(Tensor.subtract(2))
#Multiply  3 to all Elements present in the Tensor
print(Tensor*3)
print(Tensor.multiply(3))
#Divide 2 to all Elements present in the Tensor
print(Tensor/2)
print("prabhakar")

tensor([11, 12, 13, 14])
tensor([11, 12, 13, 14])
tensor([-1,  0,  1,  2])
tensor([-1,  0,  1,  2])
tensor([ 3,  6,  9, 12])
tensor([ 3,  6,  9, 12])
tensor([0.5000, 1.0000, 1.5000, 2.0000])
prabhakar
