In [37]:
import torch
print(torch.__version__)
print(torch.__version__)

2.8.0+cpu
2.8.0+cpu


In [35]:
import torch
Tensor=torch.tensor([1,2,3,4])
#Adding the 10 to all Elements present in the Tensor
#Note:Adding the Values by using + operator it will not update the Original Tensor ,Just it will add the value to Every Element in the Vector
print(Tensor+10)
#Note:When Add The Element by using the add_() function it will add the Value to every Element present in the Tensor and Also Modify the Original Tensor.
print(Tensor.add(10))
#Subtracting the 2 to all Elements present in the Tensor
print(Tensor-2)
print(Tensor.subtract(2))
#Multiply  3 to all Elements present in the Tensor
print(Tensor*3)
print(Tensor.multiply(3))
#Divide 2 to all Elements present in the Tensor
print(Tensor/2)


tensor([11, 12, 13, 14])
tensor([11, 12, 13, 14])
tensor([-1,  0,  1,  2])
tensor([-1,  0,  1,  2])
tensor([ 3,  6,  9, 12])
tensor([ 3,  6,  9, 12])
tensor([0.5000, 1.0000, 1.5000, 2.0000])


In [3]:
#Elements wise Multiplications  and NOTE:Both should be Tensors only
a=torch.tensor([1,2,3,4])
#We can use any of these for getting the Product Matrix
print(torch.mul(a,Tensor))
print(a*Tensor)

tensor([ 1,  4,  9, 16])
tensor([ 1,  4,  9, 16])
