In [42]:
#Finding Derivative by using Function
# def dy_dx(x1):
#     return 2*x1
# dy_dx(3)


In [43]:
#Auto_grad is a core components of pytorch that provides automatic differential for Tensors
#requires_grad is By default is False ,if we want to perform gradient to the Tensor we have to set requires_grad=True
#Note:Autograd is only performs on float and complex number of Tensors only
import torch
from torch.nn.functional import binary_cross_entropy
x=torch.tensor(3.0,requires_grad=True)

In [44]:
y=x**2
#Output:This Output will specifies How derivative will performs to the given Tensor
# tensor(9., grad_fn=<PowBackward0>)

y.backward()
x.grad

tensor(6.)

In [45]:
# #Using Two values of the Derivative
# import math
# def dz_dx(x1):
#     return 2*x1*math.cos(x1**2)
# dz_dx(3)
import torch
x=torch.tensor(3.0,requires_grad=True)
y=x**2
z=torch.sin(y)
z.backward()
x.grad

tensor(-5.4668)

In [46]:
#Finding Whether The student Got placed at campus drive based on there CGPA
import torch
#inputs
x=torch.tensor(6.7)#Input Feature
y=torch.tensor(0.0)#True Label(Binary)

w=torch.tensor(1.0)#Weight
b=torch.tensor(0.0)#Bias



In [47]:
#Binarycross Entropy Loss for Scalar
def Binary_cross_Entropy(prediction,Target):
    epsilon=1e-8 #To prevent Log(0)
    prediction=torch.clamp(prediction,epsilon,1-epsilon)
    return -(Target*torch.log(prediction)+(1-Target)*torch.log(1-prediction))

In [48]:
#Forward Pass
z=w*x+b #Weighted sum (Linear Part)
y_preds=torch.sigmoid(z)
y_preds

tensor(0.9988)

In [49]:
#Computing the Binary cross Entropy Loss
Loss=Binary_cross_Entropy(y_preds,y)
Loss


tensor(6.7012)

In [50]:
#Derivatives
#1.dL/d(y_preds):Loss with respect to prediction (y_preds)
dLoss_dy_Preds=(y_preds-y)/(y_preds*(1-y_preds))
#2.dy_pred/dz:prediction (y_pred) with respect to z (sigmoid)
dy_Preds_dz=y_preds*(1-y_preds)
#3.dz/dw and dz/db :z with respect to w and b
dz_dw=x
dz_db=1
dL_dw=dLoss_dy_Preds*dy_Preds_dz*dz_dw
dL_db=dLoss_dy_Preds*dy_Preds_dz*dz_db

In [51]:
print(f'The Manual Gradient of the Loss w.r.t to weights is {dL_dw}')
print(f'The Manual Gradient of the Loss w.r.t to Bias is {dL_db}')


The Manual Gradient of the Loss w.r.t to weights is 6.691762447357178
The Manual Gradient of the Loss w.r.t to Bias is 0.998770534992218


Using Backward

In [52]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [53]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [54]:
w

tensor(1., requires_grad=True)

In [55]:
b

tensor(0., requires_grad=True)

In [56]:
#Forward Propagation
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [57]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [58]:
loss=Binary_cross_Entropy(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [59]:
loss.backward()

In [60]:
print(f"{w.grad}")
print(f"{b.grad}")

6.6917619705200195
0.9987704753875732


In [61]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [62]:
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [63]:
y.backward()

In [64]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

Clearing Gradient

In [65]:
import torch
a=torch.tensor(2.0,requires_grad=True)

In [66]:
#Forward pass
b=a**2
b

tensor(4., grad_fn=<PowBackward0>)

In [67]:
#Backward Pass
b.backward()

In [68]:
#a.grad will accumulate the all gradient in it,if run 2nd time the new gradient is added to the previous stored gradient
a.grad

tensor(4.)

In [69]:
a.grad.zero_()

tensor(0.)

Disable the gradient Tracking

In [70]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [71]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [72]:
y.backward()
x.grad


tensor(4.)

Option1-requires_grad_(False)<br>
Option2-detach()<br>
Option3-torch.no_grad()

In [73]:
x.requires_grad_(False)
#in output attribute require_grad=True is Not There
x
#This will Give the Error
# y.backward()

tensor(2.)

In [74]:
#Option2:detach() we use this function to create the new Tensor ,that should have the requires_grad is equal to False
x=torch.tensor(2.0,requires_grad=True)
print("The Tensor which has requires_grad=True",x)
z=x.detach()
print(f"The Tensor Created by detach() function which has doesn't have the requires_grad=True and only has Tensor {z}")

The Tensor which has requires_grad=True tensor(2., requires_grad=True)
The Tensor Created by detach() function which has doesn't have the requires_grad=True and only has Tensor 2.0


In [75]:
#Here the gradient is work on x Tensor
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [76]:
#But to z Tensor the Gradient is Not Work
y1=z**2
y1

tensor(4.)

In [77]:
#Work properly
y.backward()
#Produce Error
# y1.backward()
x.grad

tensor(4.)

In [78]:
x.grad.zero_()

tensor(0.)

In [79]:
#Option3:torch.no_grad():
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [80]:
with torch.no_grad():
    y=x**2
    #y.backward() gives Error
y

tensor(4.)

In [81]:
#performing autograd on Vectors And Matrix
import torch
x=torch.tensor([1,2,3,4.],requires_grad=True)
a=torch.tensor([[1,2,3.],
                [4,5,6.]],requires_grad=True)
y=x**2+3*x
b=a**3+5*a
y.sum().backward()
b.sum().backward()
print("The Gradient of the x Tensor is ",x.grad)
print("The Gradient of the a Tensor is ",a.grad)

The Gradient of the x Tensor is  tensor([ 5.,  7.,  9., 11.])
The Gradient of the a Tensor is  tensor([[  8.,  17.,  32.],
        [ 53.,  80., 113.]])


In [8]:
import torch
a=torch.tensor([3.,4.],dtype=torch.float32)
b=torch.tensor([4.,5.],dtype=torch.float32)
Complex=torch.complex(a,b)
print(Complex)
print(type(complex))


tensor([3.+4.j, 4.+5.j])
<class 'type'>


In [12]:
import torch
# Create a complex tensor with requires_grad=True
z = torch.tensor(1.0 + 2.0j, requires_grad=True)
# Define a complex-valued function leading to a real-valued loss
# For instance, a simple squared magnitude
loss = (z * z.conj()).real
print(loss)
# Compute gradients
loss.backward()
# Access the gradient
print(z.grad)

tensor(5., grad_fn=<SelectBackward0>)
tensor(2.+4.j)
