In [4]:
import torch
Tensor=torch.rand(2,3)
print(Tensor)


tensor([[0.7454, 0.4420, 0.7310],
        [0.9196, 0.1850, 0.4945]])


In [12]:
Scalar=torch.tensor(3)
print(Scalar.size())
print(Scalar.ndim)
#Getting the Scaler Value
print(Scalar.item())


torch.Size([])
0
3


In [20]:
#Vector Mathematical and physical Entity which possesses both magnitude and Direction
Vector=torch.tensor([2,4,6,8,10],requires_grad=True,dtype=torch.float64)
print(Vector)
print(Vector.shape)
print(Vector.size())
print(Vector.dtype)
print(Vector.dim())

tensor([ 2.,  4.,  6.,  8., 10.], dtype=torch.float64, requires_grad=True)
torch.Size([5])
torch.Size([5])
torch.float64
1


In [27]:
#Array:The Rectangular arrangement of Elements is Called Array or Matrix
Array=torch.tensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]],requires_grad=True,dtype=torch.float64)
print(Array)
print(Array.size())
print(Array.shape)
print(Array.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64, requires_grad=True)
torch.Size([3, 3])
torch.Size([3, 3])
torch.float64


In [30]:
#Creating the Random Tensor
Random_Tensor=torch.rand(size=(2,3),dtype=torch.float64)
print("The Random Tensor is ",Random_Tensor)
print("The Data type of the Tensor is ",Random_Tensor.dtype)

The Random Tensor is  tensor([[0.0851, 0.4442, 0.6804],
        [0.2170, 0.3792, 0.0936]], dtype=torch.float64)
The Data type of the Tensor is  torch.float64


In [33]:
#Creating the Zeros Tensor
Zeros=torch.zeros(size=(3,4))
print(Zeros,Zeros.size(),Zeros.ndim)
print(Zeros.shape)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.Size([3, 4]) 2
torch.Size([3, 4])


In [38]:
Zeros_To_Tensor=torch.arange(0,10)
print(Zeros_To_Tensor)
#Creating the Tensor of the Zeros and The input Should be Tensor Only
Ten_Zeros=torch.zeros_like(input=Zeros_To_Tensor)
print(Ten_Zeros)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [60]:
#NOTE:Default Datatype of the Tensor is float32
float_32_Tensor=torch.tensor([2,3,4,5.],requires_grad=False,device=None,dtype=torch.float32)
print(float_32_Tensor)
print(float_32_Tensor.device)
print(float_32_Tensor.dtype)

tensor([2., 3., 4., 5.])
cpu
torch.float32
