In [ ]:
import torch
Zeros_Tensor=torch.zeros(size=(3,4,3))
print(Zeros_Tensor)
Ones_Tensor=torch.ones(size=(2,3,4))
print(Ones_Tensor)

In [ ]:
#printing the Random Tensors
Random_Tensor=torch.rand(size=(2,3,2),dtype=torch.float64)
print(Random_Tensor)
print("The Datatype of the Random_Tensor is ",Random_Tensor.dtype)

In [18]:
import torch
print(torch.__version__)
Tensor_Zeros=torch.zeros(size=(2,3,4))
print(Tensor_Zeros)
Tensor_Ones=torch.ones(size=(2,3,4))
print(Tensor_Ones)
Random_Tensor=torch.rand(size=(2,3,4))
print(Random_Tensor)
RandN_Tensor=torch.randn(size=(2,3,4))
print(RandN_Tensor)

2.7.1a0
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0.2799, 0.5233, 0.1013, 0.9542],
         [0.5749, 0.3433, 0.0052, 0.3223],
         [0.2499, 0.7586, 0.4902, 0.7274]],

        [[0.1198, 0.4160, 0.3858, 0.0987],
         [0.4042, 0.8865, 0.3584, 0.6681],
         [0.3397, 0.3092, 0.5541, 0.7760]]])
tensor([[[-1.5441e-03, -2.8021e-01,  3.1292e-03,  3.5548e-01],
         [ 1.1729e-01,  8.3904e-01, -4.7819e-01, -2.9893e-01],
         [ 1.1059e+00,  8.1772e-01,  1.6100e+00,  1.1385e+00]],

        [[-2.5858e-02, -2.9399e-01,  7.1569e-01, -1.1540e-01],
         [-1.1030e-01, -8.3341e-01,  1.9747e+00, -6.1896e-01],
         [ 4.1909e-01, -1.2606e+00,  2.0967e-01,  3.8488e-01]]])
