In [137]:
#Finding Whether the Student placed in campus drive or not!!
import torch
#Input Features
x=torch.tensor(6.7)
#output Labels
y=torch.tensor(0.0)
#Weights
w=torch.tensor(1.0 )
#Bias
b=torch.tensor(0.0)

In [138]:
#BinaryEntropy Loss For Scalar
# def Binary_Entropy_Loss(prediction,Target):
#     epsilon=1e-8
#     prediction=torch.clamp(prediction,epsilon,1-epsilon)
#     return -(Target*torch.log(prediction)+(1-Target)*torch.log(1-prediction))
def Binary_Cross_Entropy(prediction,Target):
    epsilon=1e-8
    prediction=torch.clamp(prediction,epsilon,1-epsilon)
    return -(Target*torch.log(prediction)+(1-Target)*torch.log(1-prediction))

In [139]:
#Forward Pass
z=w*x+b
y_preds=torch.sigmoid(z)
y_preds


tensor(0.9988)

In [140]:
#Compute the Binary Entropy Loss
Loss=Binary_Cross_Entropy(y_preds,y)
Loss

tensor(6.7012)

In [141]:
#Derivative of the Loss with respect to y_preds
dLoss_dy_preds=(y_preds-y)/(y_preds*(1-y_preds))
dy_preds_dz=y_preds*(1-y_preds)
dz_dw=x
dz_db=1
dLoss_dw=dLoss_dy_preds*dy_preds_dz*dz_dw
dLoss_db=dLoss_dy_preds*dy_preds_dz*dz_db
print(f'Loss with respect to w is {dLoss_dw}')
print(f'Loss with respect to b is {dLoss_db}')

Loss with respect to w is 6.691762447357178
Loss with respect to b is 0.998770534992218


In [142]:
import torch
x=torch.tensor(6.7)
y=torch.tensor(0.0)
#weights
w=torch.tensor(1.0,requires_grad=True)
#Bias
b=torch.tensor(0.0,requires_grad=True)

In [143]:
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [144]:
y_preds=torch.sigmoid(z)
y_preds

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [145]:
Loss=Binary_Cross_Entropy(y_preds,y)
Loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [146]:
Loss.backward()

In [147]:

print(f"Loss wrt weights {w.grad}")


Loss wrt weights 6.6917619705200195


In [148]:
print(f"Loss wrt bias {b.grad}")

Loss wrt bias 0.9987704753875732


#Simple Example

In [163]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [177]:
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [178]:
y.mean().backward()

In [179]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [185]:
x.grad.zero_()
x.grad.zero_()

tensor([0., 0., 0.])