In [ ]:
# #Work Flow of the Pytorch
# import torch
# import matplotlib.pyplot as plt
# from torch import nn
# weights=0.7
# bias=0.3
# start=0
# end=1
# step=0.02
# X=torch.arange(start, end, step).unsqueeze(dim=1)
# y=X*weights+bias
# #Spliting the Data into the Training and Testing
# splittingData=int(0.8*len(X))
# splittingData
# X_Data,X_Test=X[:splittingData],X[splittingData:]
# y_Data,y_Test=y[:splittingData],y[splittingData:]
# print(len(X_Data),len(y_Data))
# print(len(X_Test),len(y_Test))
# def plot_prediction(Train_Data=X_Data,
#                     Train_Labels=y_Data,
#                     Test_Data=X_Test,
#                     Test_Labels=y_Test,
#                     prediction=None):
#     plt.figure(figsize=(10,7))
#     plt.scatter(Train_Data,Train_Labels,c="b",s=20,label="Training Data")
#     plt.scatter(Test_Data,Test_Labels,c="g",s=20,label="Testing Data")
#     plt.legend(prop={"size":20});
# plot_prediction()


In [ ]:
#Work Flow of the Pytorch
import torch
import matplotlib.pyplot as plt
from torch import nn
weight=0.7
bias=0.3
start=0
end=1
step=0.02
X=torch.arange(start,end,step).unsqueeze(dim=1)
y=X*weight+bias
#Spliting the Data into Training And Testing
splittingData=int(0.8 * len(X))
X_Train,X_Test=X[:splittingData],X[splittingData:]
y_Train,y_Test=y[:splittingData],y[splittingData:]
def plot_prediction(Train_Data=X_Train,
                    Train_Label=y_Train,
                    Test_Data=X_Test,
                    Test_Label=y_Test,
                    prediction=None
                    ):
    plt.figure(figsize=(10,7))
    plt.scatter(Train_Data,Train_Label,c="b",s=20,label="Training Data")
    plt.scatter(Test_Data,Test_Label,c="g",s=20,label="Testing Data")
    if prediction is not None:
        plt.scatter(Test_Label,prediction,c="r",s=20,label="Training Data")

    plt.legend(prop={"size":20});
plot_prediction()

In [ ]:
# class LinearRegressionModel(nn.Module):
#     def __init__(self):
#         super().__init__()
#         self.weights=nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
#         self.bias=nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
#     def forward(self,x:torch.Tensor)->torch.Tensor:
#         return self.weights*x+self.bias

In [46]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights=nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
        self.bias=nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
    def forward(self,x:torch.Tensor)->torch.Tensor:
        return self.weights*x+self.bias

In [ ]:
torch.manual_seed(42)
model_0=LinearRegressionModel()
list(model_0.parameters())
model_0.state_dict()

In [ ]:
with torch.inference_mode():
    y_preds=model_0(X_Test)
print(f'The prediction of the Model is {y_preds}')

In [ ]:
print(f'The number of  TrainingSamples are {len(X_Test)}')
print(f'The number of Testing Samples are {len(y_Test)}')
plot_prediction(prediction=y_preds)

In [37]:
#Finding the Loss of the model
print(y_preds)
print(y_Test)
y_Test-y_preds

tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]])
tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])


tensor([[0.4618],
        [0.4691],
        [0.4764],
        [0.4836],
        [0.4909],
        [0.4982],
        [0.5054],
        [0.5127],
        [0.5200],
        [0.5272]])