In [2]:
import torch
print(torch.__version__)
Scalar=torch.tensor(2)
print(Scalar)
print(Scalar.ndim)
print(Scalar.shape)
print(Scalar.size())
#Vector:Can be defined as Mathematical and Physical entity that possesses both magnitude and Direction...
Vector=torch.tensor([1,2,3,4],dtype=torch.float32)
print(Vector)
Vector=torch.tensor([2,4,6,8],dtype=torch.float64)
print(Vector.dtype)
print(Vector.ndim)
print(Vector.shape)
print(Vector.size())
#Matrix:A Rectangular Arrangement of the Elements is Called Matrix
Matrix=torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(Matrix.dtype)
print(Matrix.shape)
print(Matrix.size)
print(Matrix)
#Tensors:Tensors Can be defined As Combining the Several Matrix or MultiDimensional Array is Called Tensor
Tensor=torch.tensor([[[1,2,7],
                      [3,4,7]],
                     [[5,6,6],
                      [7,8,8]]])
print(Tensor.size())
print(Tensor.dim())

2.7.1a0
tensor(2)
0
torch.Size([])
torch.Size([])
tensor([1., 2., 3., 4.])
torch.float64
1
torch.Size([4])
torch.Size([4])
torch.int64
torch.Size([3, 3])
<built-in method size of Tensor object at 0x7f61db43ea80>
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([2, 2, 3])
3


In [3]:
#Creating the Random Tensors
Random_Tensor=torch.rand(size=(2,3,2))
print(Random_Tensor)

tensor([[[0.0638, 0.5745],
         [0.0928, 0.7142],
         [0.6174, 0.8919]],

        [[0.1738, 0.8769],
         [0.4458, 0.4884],
         [0.1226, 0.0424]]])


In [10]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(2, 2).to(device)
    print("Tensor on GPU:", x)
else:
    print("GPU not available, using CPU")


GPU not available, using CPU
