In [72]:
import torch
Random_Tensor=torch.rand(size=(3,4))
print(Random_Tensor)
Zeros=torch.zeros(size=(3,4))
print(Zeros)
Ones=torch.ones(size=(3,4))
print(Ones)

tensor([[0.3749, 0.5005, 0.1972, 0.8343],
        [0.4996, 0.1321, 0.3354, 0.6633],
        [0.7363, 0.9674, 0.4761, 0.2491]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
