In [1]:
import torch
print(torch.__version__)

2.8.0+cpu


In [2]:
#Scalar
Scalar=torch.tensor(2)
print("The Scalar Value is ",Scalar)
print("The Dimensional of the Scalar is ",Scalar.ndim)
print("The Shape of the Scalar is ",Scalar.shape)
print("The Printing the scalar value is ",Scalar.item())
#Vector: It is Mathematical and Physical entity that possesses (which have or own )both magnitube(size or length) and Direction
Vector=torch.tensor([1,2,3,4])
print("The Vector is ",Vector)
print("The Shape of the Vector is" ,Vector.shape)
print("The Dimensional fo the Vector is ",Vector.shape)
print("The Size of the Vector is ",Vector.size)
#Matrix:The Rectangular Arrnagement of the elements is Called Matrix.
Matrix=torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print("The Matrix is ",Matrix)
print("The Shape of the Matrix is ",Matrix.shape)
print("The Dimensional of the Matrix is ",Matrix.ndim)
#Tensor:Tensor can be Defined as combining the several matrixes or Multidimensional array is Called Tensor
Tensor=torch.tensor([[[1,2],
                      [3,4]],
                      [[5,6],
                       [7,8]],
                      [[8,9],
                       [10,11]]])
print("The Tensor is ",Tensor)
print("The Shape of the Tensor is ",Tensor.shape)
print("The Dimensional of the Tensor is ",Tensor.ndim)
print("The length of the Tensor is ",len(Tensor))

The Scalar Value is  tensor(2)
The Dimensional of the Scalar is  0
The Shape of the Scalar is  torch.Size([])
The Printing the scalar value is  2
The Vector is  tensor([1, 2, 3, 4])
The Shape of the Vector is torch.Size([4])
The Dimensional fo the Vector is  torch.Size([4])
The Size of the Vector is  <built-in method size of Tensor object at 0x7f949abd83c0>
The Matrix is  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The Shape of the Matrix is  torch.Size([3, 3])
The Dimensional of the Matrix is  2
The Tensor is  tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 8,  9],
         [10, 11]]])
The Shape of the Tensor is  torch.Size([3, 2, 2])
The Dimensional of the Tensor is  3
The length of the Tensor is  3


In [3]:
#Creating the Random Tensor
random_tensor=torch.rand(size=(3,4),dtype=torch.float64)
print("The Random Tensor is ",random_tensor)
print("The Data type of the Tensor is ",random_tensor.dtype)


The Random Tensor is  tensor([[0.6355, 0.7924, 0.0539, 0.5423],
        [0.3895, 0.1968, 0.5473, 0.4868],
        [0.7391, 0.0048, 0.2662, 0.7499]], dtype=torch.float64)
The Data type of the Tensor is  torch.float64


In [4]:
#Creating the Zeros Tensor
Zeros=torch.zeros(size=(3,4))
print(Zeros,Zeros.dtype,Zeros.ndim,Zeros.shape)
#Creating the ones Tensor
Ones=torch.ones(size=(4,3,4))
print(Ones)
print("The Shape of the Tensor is ",Ones.shape)
print("The Dimensional fo the Array",Ones.ndim)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32 2 torch.Size([3, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
The Shape of the Tensor is  torch.Size([4, 3, 4])
The Dimensional fo the Array 3


In [5]:
Zeros_to_ten_deprecatedd=torch.arange(0,10)
print(Zeros_to_ten_deprecatedd)
#Creating Tensor of the Zeros And The input should be Tensor only
ten_Zeros=torch.zeros_like(input=Zeros_to_ten_deprecatedd)
print(ten_Zeros)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [6]:
#Note:Default Datatype of the Tensor is float32
float_32_Tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
print("The Tensor type float is",float_32_Tensor)
print("The Datatype of Tensor is ",float_32_Tensor.dtype)
print("The shape of the Tensor is ",float_32_Tensor.shape)
print("The Device which we used to run the torch is ",float_32_Tensor.device)

The Tensor type float is tensor([3., 6., 9.])
The Datatype of Tensor is  torch.float32
The shape of the Tensor is  torch.Size([3])
The Device which we used to run the torch is  cpu


In [7]:
#we can change the datatype of the Tensor
Tensor1=torch.tensor([1,2,3,4])
Tensor2=torch.tensor([1,2,3,4],dtype=torch.float16)
Tensor3=torch.tensor([1,2,3,4],dtype=torch.int64)
Tensor4=torch.tensor([1,2,3,4],dtype=torch.int16)
print(Tensor.dtype)
print(Tensor2.dtype)
print(Tensor3.dtype)
print(Tensor4.dtype)

torch.int64
torch.float16
torch.int64
torch.int16


In [8]:
some_Tensor=torch.rand(size=(4,5))
print(some_Tensor)
print(f'shape of the Tensor is {some_Tensor.shape}')
print(f'Datatype of the Tensor is {some_Tensor.dtype}')
print(f'The Device Tensor is Stored on {some_Tensor.device}')


tensor([[0.9640, 0.4408, 0.9914, 0.0013, 0.4813],
        [0.8770, 0.7776, 0.9876, 0.0262, 0.7507],
        [0.0705, 0.4518, 0.6487, 0.8446, 0.8270],
        [0.6169, 0.1758, 0.2216, 0.6438, 0.2992]])
shape of the Tensor is torch.Size([4, 5])
Datatype of the Tensor is torch.float32
The Device Tensor is Stored on cpu
