In [3]:
import torch
print(torch.__version__)
print(torch.__version__)
print(torch.__version__)

2.7.1a0
2.7.1a0
2.7.1a0


In [3]:
#Scalar:Single Value
Scalar=torch.tensor(2)
print("The Scalar Value is ",Scalar)
print("The Dimensional of the Scalar is ",Scalar.ndim)
print("The Shape of the Scalar is ",Scalar.shape)
print("The Printing the scalar value is ",Scalar.item())
#Vector: It is Mathematical and Physical entity that possesses (which have or own )both magnitube(size or length) and Direction
Vector=torch.tensor([1,2,3,4])
print("The Vector is ",Vector)
print("The Shape of the Vector is" ,Vector.shape)
print("The Dimensional fo the Vector is ",Vector.ndim)
print("The Size of the Vector is ",Vector.size)
#Matrix:The Rectangular Arrangement of the elements is Called Matrix.
Matrix=torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print("The Matrix is ",Matrix)
print("The Shape of the Matrix is ",Matrix.shape)
print("The Dimensional of the Matrix is ",Matrix.ndim)
#Tensor:Tensor can be Defined as combining the several matrixes or Multidimensional array is Called Tensor
Tensor=torch.tensor([[[1,2],
                      [3,4]],
                      [[5,6],
                       [7,8]],
                      [[8,9],
                       [10,11]]])
print("The Tensor is ",Tensor)
print("The Shape of the Tensor is ",Tensor.shape)
print("The Dimensional of the Tensor is ",Tensor.ndim)
print("The length of the Tensor is ",len(Tensor))

The Scalar Value is  tensor(2)
The Dimensional of the Scalar is  0
The Shape of the Scalar is  torch.Size([])
The Printing the scalar value is  2
The Vector is  tensor([1, 2, 3, 4])
The Shape of the Vector is torch.Size([4])
The Dimensional fo the Vector is  1
The Size of the Vector is  <built-in method size of Tensor object at 0x7fe88d04ada0>
The Matrix is  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The Shape of the Matrix is  torch.Size([3, 3])
The Dimensional of the Matrix is  2
The Tensor is  tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 8,  9],
         [10, 11]]])
The Shape of the Tensor is  torch.Size([3, 2, 2])
The Dimensional of the Tensor is  3
The length of the Tensor is  3


In [3]:
#Creating the Random Tensor
random_tensor=torch.rand(size=(3,4),dtype=torch.float64)
print("The Random Tensor is ",random_tensor)
print("The Data type of the Tensor is ",random_tensor.dtype)


The Random Tensor is  tensor([[0.7968, 0.2195, 0.5478, 0.8312],
        [0.9090, 0.6185, 0.1507, 0.1722],
        [0.8147, 0.3270, 0.7337, 0.8262]], dtype=torch.float64)
The Data type of the Tensor is  torch.float64


In [4]:
#Creating the Zeros Tensor
Zeros=torch.zeros(size=(3,4))
print(Zeros,Zeros.dtype,Zeros.ndim,Zeros.shape)
#Creating the ones Tensor
Ones=torch.ones(size=(4,3,4))
print(Ones)
print("The Shape of the Tensor is ",Ones.shape)
print("The Dimensional fo the Array",Ones.ndim)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32 2 torch.Size([3, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
The Shape of the Tensor is  torch.Size([4, 3, 4])
The Dimensional fo the Array 3


In [5]:
Zeros_to_ten_deprecatedd=torch.arange(0,10)
print(Zeros_to_ten_deprecatedd)
#Creating Tensor of the Zeros And The input should be Tensor only
ten_Zeros=torch.zeros_like(input=Zeros_to_ten_deprecatedd)
print(ten_Zeros)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


Retriving the Information from Tensor

In [6]:
#Note:Default Datatype of the Tensor is float32
float_32_Tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
print("The Tensor type float is",float_32_Tensor)
print("The Datatype of Tensor is ",float_32_Tensor.dtype)
print("The shape of the Tensor is ",float_32_Tensor.shape)
print("The Device which we used to run the torch is ",float_32_Tensor.device)

The Tensor type float is tensor([3., 6., 9.])
The Datatype of Tensor is  torch.float32
The shape of the Tensor is  torch.Size([3])
The Device which we used to run the torch is  cpu


Changing the Datatype

In [7]:
#we can change the datatype of the Tensor
Tensor1=torch.tensor([1,2,3,4])
Tensor2=torch.tensor([1,2,3,4],dtype=torch.float16)
Tensor3=torch.tensor([1,2,3,4],dtype=torch.int64)
Tensor4=torch.tensor([1,2,3,4],dtype=torch.int16)
print(Tensor.dtype)
print(Tensor2.dtype)
print(Tensor3.dtype)
print(Tensor4.dtype)

torch.int64
torch.float16
torch.int64
torch.int16


In [8]:
some_Tensor=torch.rand(size=(4,5))
print(some_Tensor)
print(f'shape of the Tensor is {some_Tensor.shape}')
print(f'Datatype of the Tensor is {some_Tensor.dtype}')
print(f'The Device Tensor is Stored on {some_Tensor.device}')


tensor([[0.3421, 0.8567, 0.1065, 0.4724, 0.9756],
        [0.9107, 0.9343, 0.0124, 0.1229, 0.1409],
        [0.9186, 0.1074, 0.8957, 0.5371, 0.0899],
        [0.3079, 0.5848, 0.4655, 0.3432, 0.6436]])
shape of the Tensor is torch.Size([4, 5])
Datatype of the Tensor is torch.float32
The Device Tensor is Stored on cpu


Aggregation Operations

In [16]:
#Finding the Min,Max,Sum,and Mean of the Tensor
#Creating the Tensor using arange
x=torch.arange(10,101,10)
print(x)
#Now Aggregation Functions are
print(f'The minimum element is {torch.min(x)}')
# print(f'The minimum element is {x.mean()}')
print(f'The Maximum Element is {torch.max(x)}')
# print(f'The Maximum Element is {x.max()}')
print(f'The Sum of the Tensor Element is {torch.sum(x)}')
print(f'The mean of the Tensor Element  is {x.type(torch.float32).mean()}')

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
The minimum element is 10
The Maximum Element is 100
The Sum of the Tensot Element is 550
The mean of the Tensor Element  is 55.0


In [22]:
x=torch.arange(10,100,10)
print("The Torch is ",x)
#Aggregation functions
print("The minimum Elements of the Tensor is ",torch.min(x))
print("The maximum Element is of the  Tensor is ",torch.max(x))
print("The Sum of the Tensor Elements is ",torch.sum(x))
print("The mean of the Tensor Elements is ",x.type(torch.float32).mean())

The Torch is  tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
The minimum Elements of the Tensor is  tensor(10)
The maximum Element is of the  Tensor is  tensor(90)
The Sum of the Tensor Elements is  tensor(450)
The mean of the Tensor Elements is  tensor(50.)


Positional Min/Max

In [21]:
Tensor=torch.arange(1,100,15)
print(f'Tenosr is :{Tensor}')
#Return the Index of Max and Min
print(f"Index where Max value Occure {Tensor.argmax()}")
print(f"Index where Min Value Occure {Tensor.argmin()}")

Tenosr is :tensor([ 1, 16, 31, 46, 61, 76, 91])
Index where Max value Occure 6
Index where Min Value Occure 0
