Reshaping ,Staking,Squeezing and unsqueezing

In [ ]:
#Create the Tensor
import torch
x=torch.arange(1,9)
print("The Tensor is ",x)
print("The Shape of the Tensor is ",x.shape)

In [ ]:
#Adding the Extra dimensions
x_Reshaped=x.reshape(1,8)
print("The Reshaped Tensor is ",x_Reshaped)
print("The Size of the Tensor is ",x_Reshaped.shape)

In [ ]:
#We can also change the view() with torch.view()
print("The Original Tensor is ",x_Reshaped)
z=x_Reshaped.view(4,2)
print("The Tensor after appling the view to the Original Tensor",z)
print("The Shape of the Updated Tensor using view() is ",z.shape)
z[0,0]=100
z.add_(3)
print(z)
print(x_Reshaped)

In [ ]:
#Stack Tensor on top of each Tensor
T=torch.arange(1,8)
x_stacked=torch.stack([T,T,T,T],dim=0)
print(x_stacked)

Squeezing in Tensors

In [40]:
#Removing the Dimensions From the Tensors
#Note:Squeezing or Compress similar meaning
print(f"Previous Tensor is {x_Reshaped}")
print(f"The Shape of the Tenosr is {x_Reshaped.shape}")
#Removing the Extra Dimensions from the Tensors
x_Squeezing=x_Reshaped.squeeze()
print(f"New Tensor after squeezing is {x_Squeezing}")
print(f"Shape of the New Tensor is {x_Squeezing.shape}")

Previous Tensor is tensor([[103,   5,   6,   7,   8,   9,  10,  11]])
The Shape of the Tenosr is torch.Size([1, 8])
New Tensor after squeezing is tensor([103,   5,   6,   7,   8,   9,  10,  11])
Shape of the New Tensor is torch.Size([8])


Reversed Squeezing

In [41]:
#Adding the Dimensions to the Tensors
print(f"Previous Tensor is {x_Squeezing}")
print(f"Shape of the Tensor is {x_Squeezing}")
#Adding the Extra Dimension with unsqueeze()
x_unsqueezing=x_Squeezing.unsqueeze(dim=0)
print(f"New Tensor is {x_unsqueezing}")
print(f"NEw Shape is {x_unsqueezing.shape}")

Previous Tensor is tensor([103,   5,   6,   7,   8,   9,  10,  11])
Shape of the Tensor is tensor([103,   5,   6,   7,   8,   9,  10,  11])
New Tensor is tensor([[103,   5,   6,   7,   8,   9,  10,  11]])
NEw Shape is torch.Size([1, 8])


Rearrange Order of Axis

In [67]:
#Create Tensor with Specific Shape
x_original=torch.rand(size=(224,224,3))
#permute the original Tensor to Rearrange  the axis order
#The Range between -3 to 2 often Values rae -2,-1,0,1,2 only
x_permuted=x_original.permute(2,0,1)
print(f"Previous shape is {x_original.shape}")
print(f"New Shape is {x_permuted.shape}")


Previous shape is torch.Size([224, 224, 3])
New Shape is torch.Size([3, 224, 224])


Indexing:Selecting the Data from Tensors

In [74]:
#Create the Tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
print(x)
#Retriving the First of the Matrix
print(x[0])
#Retriving the First Matrix First Row
print(x[0][0])
#Retriving the First Matrix First Row And First Element
print(x[0][0][0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [85]:
#We can also Retrive the Elements by using slicing method
#Asscesing the all rows and Columns of the Tensor
print(x[:])
#Asscesing the all columns of the First Row
print(x[0,:])
#Asscesing the specific element from the First Row of the Matrix
print(x[:,0,0])
print(x[0,1:,0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1])
tensor([4, 7])
